services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command:
      - redis-server
    networks:
      - backend-network

  backend:
    image: 211i2/erica-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - backend-network
    depends_on:
      - redis

networks:
  backend-network:
    driver: bridge
