spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: '0090'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update