name: PR Build Test and Deploy to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          cache-read-only: false

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: | 
          set -e
          ./gradlew clean build -Dspring.profiles.active=local

      - name: Generate .env
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build Docker image
        run: |
          docker build \
          --build-arg SPRING_PROFILES_ACTIVE=local \
          -f Dockerfile \
          -t ${{ vars.DOCKERHUB_USERNAME}}/erica-favicon:latest .

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ vars.DOCKERHUB_PASSWORD}}

      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME}}/erica-favicon:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_HOST }}
          username: favicon
          key: ${{ vars.EC2_SSH_KEY }}
          script: |
            export SPRING_PROFILES_ACTIVE=prod
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/erica-favicon:latest   
            docker stop $(docker ps -a -q)
            docker rmi ${{ vars.DOCKERHUB_USERNAME }}/erica-favicon:latest
            docker run -d --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/erica-favicon:latest